### ISSUE TITLE
ESL support

### ISSUE THREAD

**Issue by MonterraByte** [ModOrganizer2/modorganizer-game_skyrimVR#28]
The [Skyrim VR ESL Support](https://www.nexusmods.com/skyrimspecialedition/mods/106712) mod just released, adding support for ESL plugins for Skyrim VR.

Would it be possible to enable light plugin support in MO2 when this mod is installed?

**Comment by FlayaN** [comment]
Fixed by https://github.com/ModOrganizer2/modorganizer-game_skyrimVR/pull/29
I've also tested the PR fix, works perfectly. It will even update the plugin flags and esl count directly when enabling/disabling the VR ESL mod
